<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;

/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
?>
<script>
    window.YIREO_GOOGLETAGMANAGER2_ENABLED = true;

    (function (events) {
        const initYireoGoogleTagManager2 = function () {
            events.forEach(function (eventType) {
                window.removeEventListener(eventType, initYireoGoogleTagManager2);
            });

            // Define dataLayer and the gtag function.
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}

            // Set default consent to 'denied' as a placeholder
            // Determine actual values based on your own requirements
            gtag('consent', 'default', {
                'analytics_storage': 'denied',
                'functionality_storage': 'denied',
                'personalization_storage': 'denied',
                'security_storage': 'denied',
                'ad_storage': 'denied',
                'ad_user_data': 'denied',
                'ad_personalization': 'denied',
            });

            (function (w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src = '<?= $config->getGoogleTagmanagerUrl() ?>' + '/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', '<?= $config->getId() ?>');

            // ...dispatch on elem!
            let event = new Event("default-consent-loaded", {bubbles: true}); // (2)
            window.dispatchEvent(event);
        }

        events.forEach(function (eventType) {
            window.addEventListener(eventType, initYireoGoogleTagManager2, {once: true, passive: true})
        })
    })([<?php if ($config->waitForUserInteraction() === false) : ?>'load', <?php endif; ?>'keydown', 'mouseover', 'scroll', 'touchstart', 'wheel']);
</script>

<?php if ($config->isDebug()): ?>
    <script>
        window.YIREO_GOOGLETAGMANAGER2_DEBUG = true;
        window.YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS = <?= $config->isDebugClicks() ? 'true' : 'false' ?>;
    </script>
<?php endif; ?>
